openapi: 3.0.1
info:
  title: WredTemplateProfile_1.0.0-ts.240709.1120+simulator
  version: 1.0.0

x-gui-paths:
########################################################################################################################
#   Representation Layer
########################################################################################################################
  /docs:
    get:
      operationId: docs
      summary: 'Represents Swagger API description page'
      tags:
        - RepresentationServices
      responses:
        '200':
          description: 'Swagger API description page represented'
            # Not explixitly described
        '400':
          $ref: '#/components/responses/responseForErroredOamRequests'
        '401':
          $ref: '#/components/responses/responseForErroredOamRequests'
        '403':
          $ref: '#/components/responses/responseForErroredOamRequests'
        '404':
          $ref: '#/components/responses/responseForErroredOamRequests'
        '500':
          $ref: '#/components/responses/responseForErroredOamRequests'
        default:
          $ref: '#/components/responses/responseForErroredOamRequests'

paths:
########################################################################################################################
#   Service Layer - Individual Part
########################################################################################################################
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedProfileCollection
      summary: 'Provides ProfileCollection from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'ProfileCollection provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - core-model-1-4:profile-collection
                properties:
                  core-model-1-4:profile-collection:
                    $ref: '#/components/schemas/profile-collection'
                example:
                  core-model-1-4:profile-collection:
                    profile:
                      - profile-name: 'string'
                        external-managed-id:
                          manager-identifier: 'outside specification'
                          external-managed-uuid: 'outside specification'
                        local-id: 'outside specification'
                        uuid: 'string'
                        operational-state: 'outside specification'
                        administrative-control: 'outside specification'
                        administrative-state: 'outside specification'
                        lifecycle-state: 'outside specification'
                        wred-template-profile-1-0:wred-template-profile-pac:
                          wred-template-profile-capability:
                            available-buffer-size: 0
                            drop-probability-at-threshold-low-is-avail: true
                            gentle-wred-is-avail: true
                            sensitivity-setting-is-avail: true
                            coloring-is-avail: true
                            supported-wred-protocol-list:
                              - 'string'
                            available-drop-precedence-kind-list:
                              - 'string'
                          wred-template-profile-configuration:
                            wred-template-list:
                              - affected-protocol: 'string'
                                affected-drop-precedence: 'string'
                                wred-configuration:
                                  external-label: 'string'
                                  threshold-low: 0
                                  drop-probability-at-threshold-low: 0
                                  threshold-high: 0
                                  drop-probability-at-threshold-high: 0
                                  gentle-wred-is-on: true
                                  threshold-gentle: 0
                                  sensitivity: 0
                                  coloring-is-on: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedProfile
      summary: 'Provides Profile from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'Profile provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - core-model-1-4:profile
                properties:
                  core-model-1-4:profile:
                    type: array
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/profile'
                example:
                  core-model-1-4:profile:
                    - profile-name: 'string'
                      external-managed-id:
                        manager-identifier: 'outside specification'
                        external-managed-uuid: 'outside specification'
                      local-id: 'outside specification'
                      uuid: 'string'
                      operational-state: 'outside specification'
                      administrative-control: 'outside specification'
                      administrative-state: 'outside specification'
                      lifecycle-state: 'outside specification'
                      wred-template-profile-1-0:wred-template-profile-pac:
                        wred-template-profile-capability:
                          available-buffer-size: 0
                          drop-probability-at-threshold-low-is-avail: true
                          gentle-wred-is-avail: true
                          sensitivity-setting-is-avail: true
                          coloring-is-avail: true
                          supported-wred-protocol-list:
                            - 'string'
                          available-drop-precedence-kind-list:
                            - 'string'
                        wred-template-profile-configuration:
                          wred-template-list:
                            - affected-protocol: 'string'
                              affected-drop-precedence: 'string'
                              wred-configuration:
                                external-label: 'string'
                                threshold-low: 0
                                drop-probability-at-threshold-low: 0
                                threshold-high: 0
                                drop-probability-at-threshold-high: 0
                                gentle-wred-is-on: true
                                threshold-gentle: 0
                                sensitivity: 0
                                coloring-is-on: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/wred-template-profile-pac/wred-template-profile-capability/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedWredTemplateProfileCapability
      summary: 'Provides WredTemplateProfileCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'WredTemplateProfileCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - wred-template-profile-1-0:wred-template-profile-capability
                properties:
                  wred-template-profile-1-0:wred-template-profile-capability:
                    $ref: '#/components/schemas/wred-template-profile-capability'
                example:
                  wred-template-profile-1-0:wred-template-profile-capability:
                    available-buffer-size: 0
                    drop-probability-at-threshold-low-is-avail: true
                    gentle-wred-is-avail: true
                    sensitivity-setting-is-avail: true
                    coloring-is-avail: true
                    supported-wred-protocol-list:
                      - 'string'
                    available-drop-precedence-kind-list:
                      - 'string'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/wred-template-profile-pac/wred-template-profile-configuration/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedWredTemplateProfileConfiguration
      summary: 'Provides WredTemplateProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'WredTemplateProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - wred-template-profile-1-0:wred-template-profile-configuration
                properties:
                  wred-template-profile-1-0:wred-template-profile-configuration:
                    $ref: '#/components/schemas/wred-template-profile-configuration'
                example:
                  wred-template-profile-1-0:wred-template-profile-configuration:
                    wred-template-list:
                      - affected-protocol: 'string'
                        affected-drop-precedence: 'string'
                        wred-configuration:
                          external-label: 'string'
                          threshold-low: 0
                          drop-probability-at-threshold-low: 0
                          threshold-high: 0
                          drop-probability-at-threshold-high: 0
                          gentle-wred-is-on: true
                          threshold-gentle: 0
                          sensitivity: 0
                          coloring-is-on: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

  /operations/create-wred-template-profile/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreateWredTemplateProfile
      summary: 'Creates new instance of WredTemplateProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'New instance of WredTemplateProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - created-wred-template-profile
                properties:
                  created-wred-template-profile:
                    type: string
                example:
                  created-wred-template-profile: 'string'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /operations/add-or-modify-wred-profile/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postAddOrModifyWredProfile
      summary: 'Adds or modifies an existing WRED profile inside an existing instance of WredTemplateProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - wred-template-profile-to-be-modified
                - affected-protocol
                - affected-drop-precedence
              properties:
                wred-template-profile-to-be-modified:
                  type: string
                affected-protocol:
                  type: string
                affected-drop-precedence:
                  type: string
                external-label:
                  type: string
                threshold-low:
                  type: string
                drop-probability-at-threshold-low:
                  type: string
                threshold-high:
                  type: string
                drop-probability-at-threshold-high:
                  type: string
                gentle-wred-is-on:
                  type: boolean
                threshold-gentle:
                  type: string
                sensitivity:
                  type: string
                coloring-is-on:
                  type: boolean
      responses:
        '204':
          description: 'Instance of WredTemplateProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /operations/delete-wred-profile/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeleteWredProfile
      summary: 'Deletes an existing WRED profile inside an existing instance of WredTemplateProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - wred-template-profile-to-be-modified
                - affected-protocol
                - affected-drop-precedence
              properties:
                wred-template-profile-to-be-modified:
                  type: string
                affected-protocol:
                  type: string
                affected-drop-precedence:
                  type: string
      responses:
        '204':
          description: 'Instance of WredTemplateProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /operations/delete-wred-template-profile/:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeleteWredTemplateProfile
      summary: 'Deletes an instance of WredTemplateProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - obsolete-wred-template-profile
              properties:
                obsolete-wred-template-profile:
                  type: string
      responses:
        '204':
          description: 'Instance of WredTemplateProfile deleted'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

########################################################################################################################
#   Service Layer - Basic Part
########################################################################################################################

########################################################################################################################
#   OAM Layer - Individual Part
########################################################################################################################

########################################################################################################################
#   OAM Layer - Basic Part
########################################################################################################################

########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    uuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within the device'
    uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
    localId:
      name: localId
      in: path
      required: true
      schema:
        type: string
        example: 'LP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within its list'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  headers:
    x-correlator:
      schema:
        type: string
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
    exec-time:
      schema:
        type: integer
        example: 1100
      description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    backend-time:
      schema:
        type: integer
        example: 850
      description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    life-cycle-state:
      schema:
        type: string
        enum:
          - 'EXPERIMENTAL'
          - 'OPERATIONAL'
          - 'DEPRECATED'
          - 'OBSOLETE'
          - 'UNKNOWN'
          - 'NOT_YET_DEFINED'
        example: 'EXPERIMENTAL'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    profile-collection:
      type: object
      required:
        - profile
      properties:
        profile:
          type: array
          minItems: 1
          x-key: uuid
          items:
            $ref: '#/components/schemas/profile'
    profile:
      allOf:
        - description: 'Profile class'
          type: object
          required:
            - uuid
            - profile-name
          properties:
            profile-name:
              type: string
            external-managed-id:
              type: object
              properties:
                manager-identifier:
                  type: string
                external-managed-uuid:
                  type: string
            local-id:
              type: string
            uuid:
              type: string
            name:
              type: array
            label:
              type: array
            extension:
              type: array
            operational-state:
              type: string
              enum:
                - 'core-model-1-4:OPERATIONAL_STATE_DISABLED'
                - 'core-model-1-4:OPERATIONAL_STATE_ENABLED'
            administrative-control:
              type: string
            administrative-state:
              type: string
            lifecycle-state:
              type: string
            address:
              type: array
        - description: 'Technology specific augments'
          oneOf:
            - description: 'WredTemplateProfile'
              type: object
              required:
                - wred-template-profile-1-0:wred-template-profile-pac
              properties:
                wred-template-profile-1-0:wred-template-profile-pac:
                  type: object
                  required:
                    - wred-template-profile-capability
                    - wred-template-profile-configuration
                  properties:
                    wred-template-profile-capability:
                      $ref: '#/components/schemas/wred-template-profile-capability'
                    wred-template-profile-configuration:
                      $ref: '#/components/schemas/wred-template-profile-configuration'
    wred-template-profile-capability:
      type: object
      required:
        - available-buffer-size
        - drop-probability-at-threshold-low-is-avail
        - gentle-wred-is-avail
        - sensitivity-setting-is-avail
        - coloring-is-avail
      properties:
        available-buffer-size:
          type: integer
          format: int32
        drop-probability-at-threshold-low-is-avail:
          type: boolean
        gentle-wred-is-avail:
          type: boolean
        sensitivity-setting-is-avail:
          type: boolean
        coloring-is-avail:
          type: boolean
        supported-wred-protocol-list:
          type: array
          minItems: 0
          items:
            type: string
            enum:
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_NONE'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_ETHERNET_MAC'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_VLAN'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_Q_IN_Q'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_MPLS'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_IPV4'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_IPV6'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_TCP'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_UDP'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_RTP'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_GTP_U'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_OTHERS'
              - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_NOT_YET_DEFINED'
        available-drop-precedence-kind-list:
          type: array
          minItems: 0
          items:
            type: string
            enum:
              - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_ALL'
              - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_LOW'
              - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_MEDIUM'
              - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_HIGH'
              - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_NOT_YET_DEFINED'
    wred-template-profile-configuration:
      type: object
      properties:
        wred-template-list:
          type: array
          minItems: 0
          x-key: affected-protocol affected-drop-precedence
          items:
            type: object
            required:
              - affected-protocol
              - affected-drop-precedence
              - wred-configuration
            properties:
              affected-protocol:
                type: string
                enum:
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_NONE'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_ETHERNET_MAC'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_VLAN'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_Q_IN_Q'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_MPLS'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_IPV4'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_IPV6'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_TCP'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_UDP'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_RTP'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_GTP_U'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_OTHERS'
                  - 'wred-template-profile-1-0:PROTOCOL_LAYER_TYPE_NOT_YET_DEFINED'
              affected-drop-precedence:
                type: string
                enum:
                  - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_ALL'
                  - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_LOW'
                  - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_MEDIUM'
                  - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_HIGH'
                  - 'wred-template-profile-1-0:DROP_PRECEDENCE_TYPE_NOT_YET_DEFINED'
              wred-configuration:
                type: object
                required:
                  - external-label
                  - threshold-low
                  - drop-probability-at-threshold-low
                  - threshold-high
                  - drop-probability-at-threshold-high
                  - gentle-wred-is-on
                  - threshold-gentle
                  - sensitivity
                  - coloring-is-on
                properties:
                  external-label:
                    type: string
                  threshold-low:
                    type: integer
                    format: int32
                  drop-probability-at-threshold-low:
                    type: integer
                    format: int8
                  threshold-high:
                    type: integer
                    format: int32
                  drop-probability-at-threshold-high:
                    type: integer
                    format: int8
                  gentle-wred-is-on:
                    type: boolean
                  threshold-gentle:
                    type: integer
                    format: int32
                  sensitivity:
                    type: integer
                    format: int8
                  coloring-is-on:
                    type: boolean

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
